org: yasmjm
app: aws-node-project

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**
service: scraperApi

provider:
  name: aws
  stage: dev
  region: us-east-1
  runtime: nodejs6.10
  stackName: cs-scraper-api
  disableRollback: true
functions:
  cronJob:
    handler: scraper.handler
    runtime: nodejs14.x
    memorySize: 2048
    timeout: 15
    architecture: x86_64
    events:
      - schedule:
          rate:
            - cron(15 10 * * ? *)
  lambdaApi:
    handler: index.handler
    runtime: nodejs14.x
    memorySize: 256
    timeout: 15
    events:
    - http: 
        path: /
        method: get
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
        Resource: "arn:aws:dynamodb:us-east-1:844438313671:table/Tabela"